### ISSUE TITLE
WHAT?!?!

### ISSUE THREAD

**Issue by virejdasani** [ishvaram/hackygbit#3]
Hi, I want to know how you did this. Is there a youtube video explaining this??

**Comment by ishvaram** [comment]
What exactly you wanted to understand

**Comment by virejdasani** [comment]
Hi Ishvaram, thanks for replying. I want to know how you have over 400,000 commits

**Comment by ishvaram** [comment]
its a cron which keep on committing the dummy commits. 

`git commit --allow-empty -m "Trigger notification $(date)"`
